# Generated by Django 5.0.3 on 2025-04-01 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_board_members_alter_boardinvitation_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="board",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="board_tasks",
                to="tasks.board",
            ),
        ),
    ]
